Description: Bedrock Access Gateway - OpenAI-compatible RESTful APIs for Amazon Bedrock
Transform: AWS::LanguageExtensions
Parameters:
  ApiKeyParam:
    Type: String
    Default: ""
    Description: The parameter name in System Manager used to store the API Key, leave blank to use a default key
  ImageUri:
    Type: String
    Default: ""
    Description: Specify a custom ECR image, if left blank defaults to 366590864501.dkr.ecr.us-east-1.amazonaws.com/bedrock-proxy-api:latest.
Conditions:
  UseDefaultImage: !Equals [!Ref ImageUri, ""]
Resources:
  ProxyApiHandlerServiceRoleBE71BFB1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  ProxyApiHandlerServiceRoleDefaultPolicy86681202:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - bedrock:ListFoundationModels
              - bedrock:ListInferenceProfiles
              - bedrock:ListImportedModels
            Effect: Allow
            Resource: "*"
          - Action:
              - bedrock:InvokeModel
              - bedrock:InvokeModelWithResponseStream
            Effect: Allow
            Resource:
              - arn:aws:bedrock:*::foundation-model/*
              - arn:aws:bedrock:*:*:inference-profile/*
              - arn:aws:bedrock:*:*:imported-model/*
          - Action:
              - ssm:DescribeParameters
              - ssm:GetParameters
              - ssm:GetParameter
              - ssm:GetParameterHistory
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":ssm:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :parameter/
                  - Ref: ApiKeyParam
        Version: "2012-10-17"
      PolicyName: ProxyApiHandlerServiceRoleDefaultPolicy86681202
      Roles:
        - Ref: ProxyApiHandlerServiceRoleBE71BFB1
  ProxyApiHandlerEC15A492:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - arm64
      Code:
        ImageUri: !If 
          - UseDefaultImage
          - !Join 
            - ""
            - - "366590864501.dkr.ecr."
              - !Ref AWS::Region
              - "."
              - !Ref AWS::URLSuffix
              - "/bedrock-proxy-api:latest"
          - !Ref ImageUri
      Description: Bedrock Proxy API Handler
      Environment:
        Variables:
          API_KEY_PARAM_NAME:
            Ref: ApiKeyParam
          DEBUG: "false"
          DEFAULT_MODEL:
            Fn::FindInMap:
              - ProxyRegionTable03E5BEB3
              - Ref: AWS::Region
              - model
              - DefaultValue: anthropic.claude-3-sonnet-20240229-v1:0
          DEFAULT_EMBEDDING_MODEL: cohere.embed-multilingual-v3
          ENABLE_CROSS_REGION_INFERENCE: "true"
          AWS_LWA_INVOKE_MODE: RESPONSE_STREAM
      MemorySize: 1024
      PackageType: Image
      Role:
        Fn::GetAtt:
          - ProxyApiHandlerServiceRoleBE71BFB1
          - Arn
      Timeout: 900
      Tags:
        - Key: Project
          Value: deep-seek
    DependsOn:
      - ProxyApiHandlerServiceRoleDefaultPolicy86681202
      - ProxyApiHandlerServiceRoleBE71BFB1
  ProxyApiHandlerFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      InvokeMode: RESPONSE_STREAM
      TargetFunctionArn: !GetAtt ProxyApiHandlerEC15A492.Arn
  ProxyApiHandlerInvoke2UTWxhlfyqbT5FTn5jvgbLgjFfJwzswGk55DU1HYF6C33779:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ProxyApiHandlerEC15A492
      Action: lambda:InvokeFunctionUrl
      Principal: "*"
      FunctionUrlAuthType: NONE
Mappings:
  ProxyRegionTable03E5BEB3:
    us-east-1:
      model: anthropic.claude-3-sonnet-20240229-v1:0